apiVersion: v1
kind: Secret
metadata:
    namespace: project
    name: postgres-password
data:
    postgres_password: ENC[AES256_GCM,data:RWxdAtCeMjV7kgb1xFcUL+Wx/12ZdUzvxVrD2A==,iv:DUa7uLcAjJw/ZXpyUNDqQZ+BwHOddqSuOzp02VGimWo=,tag:FOe+mNolxx5NbCbiNf32uA==,type:str]
sops:
    age:
        - recipient: age1x9cwyzskq74k8f5c6npydsvg6dcp07tntd776xqv9574jf9aj40se97sez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSnUxWlNOMytPMWpKVU1H
            Nk1mMG5XL2h6czJvaEx5WDIwYi9zRzEwRmdnCmRRVFFkcVdPZDZERXVyb3hoaXB1
            RkZIbVZ5YzlmbGlVSHBQR0xrVzRrNWMKLS0tIE16czlPN3V1UExjbGhHUkp2bGlW
            ZTVSSW9XZzcra1RtTWlOVkNzTlN2SWcKYoeNFfUwfFn20R5NJzDkBvQTs4nCH5QF
            FpIyIkEDt6XbwXgvLNfazqN9UyCKlHseeVEUe3QHdMd106+l4NjLJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T12:34:00Z"
    mac: ENC[AES256_GCM,data:WwHx8UIClBCbXahDNBELvax5GA7omoY948dK5gucOIq5QQAI+fdEegbD0wpbtuyKqz8b4qoznKfo9S1L8sHkbnNe1JfBtxy6buOqLIASpLZlcSJpFbNlHHjOuuZQYjZzH1JkkbYI67/AGjTV6CNfBr6+EYB2hZ+bBu88LTAPPb8=,iv:I+OSWphoRbrUPMvk03vvw/zHQuKyGvgWBPxLDwCKVwg=,tag:l2KqLRiz6B+xyh0Bq3rA9Q==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
